export const sample_food:any[] = [
  {
      id:'1',
      name: 'Pizza Pepperoni',
      cookTime: '10-20',
      price: 10,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'assets/food-1.jpg',
      tags: ['fastFood', 'pizza', 'lunch'],
    },
    {
      id:'2',
      name: 'Meatball',
      price: 20,
      cookTime: '20-30',
      favorite: true,
      origins: ['persia', 'middle east', 'china'],
      stars: 4.7,
      imageUrl: 'assets/food-2.jpg',
      tags: ['slowfood', 'lunch'],
    },
    {
      id:'3',
      name: 'Hamburger',
      price: 5,
      cookTime: '10-15',
      favorite: false,
      origins: ['germany', 'us'],
      stars: 3.5,
      imageUrl: 'assets/food-3.jpg',
      tags: ['fastfood', 'hamburger'],
    },
    {
      id:'4',
      name: 'Fried Potatoes',
      price: 2,
      cookTime: '15-20',
      favorite: true,
      origins: ['belgium', 'france'],
      stars: 3.3,
      imageUrl: 'assets/food-4.jpg',
      tags: ['fastfood', 'fry'],
    },
    {
      id:'5',
      name: 'Chicken Soup',
      price: 11,
      cookTime: '40-50',
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.0,
      imageUrl: 'assets/food-5.jpg',
      tags: ['slowFood', 'soup'],
    },
    {
      id:'6',
      name: 'Vegetables Pizza',
      price: 9,
      cookTime: '40-50',
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'assets/food-6.jpg',
      tags: ['fastfood', 'pizza', 'lunch'],
    },
    {
      id:'7',
      name: 'Spicy Cheese Burger',
      price: 12,
      cookTime: '20-30',
      favorite: false,
      origins: ['Indian'],
      stars: 4.0,
      imageUrl: 'assets/food-7.jpg',
      tags: ['fastfood', 'burger', 'lunch'],
    },
    {
      id:'8',
      name: 'Vegetables Magento Pizza',
      price: 9,
      cookTime: '45-50',
      favorite: false,
      origins: ['Italian', 'American'],
      stars: 4.0,
      imageUrl: 'assets/food-8.jpg',
      tags: ['fastFood', 'pizza', 'lunch'],
    },
    {
      id:'9',
      name: 'Butter chicken',
      price: 20,
      cookTime: '45-50',
      favorite: true,
      origins: ['indian'],
      stars: 4.0,
      imageUrl: 'assets/food-9.jpg',
      tags: ['slowfood', 'non-veg', 'lunch'],
    },
    {
      id:'10',
      name: 'Momos',
      price: 2,
      cookTime: '10-15',
      favorite: true,
      origins: ['China', 'Nepal'],
      stars: 4.0,
      imageUrl: 'https://junifoods.com/wp-content/uploads/2023/11/Easy-and-Simple-Chicken-Momo-Dumplings-Sajilo-Kukhura-ko-Momo-%E0%A4%B8%E0%A4%9C%E0%A4%BF%E0%A4%B2%E0%A5%8B-%E0%A4%95%E0%A5%81%E0%A4%96%E0%A5%81%E0%A4%B0%E0%A4%BE%E0%A4%95%E0%A5%8B-%E0%A4%AE%E0%A4%AE-2.jpg',
      tags: ['fastfood', 'veg', 'snacks'],
    },
    {
      id:'11',
      name: 'Samosa',
      price: 1.5,
      cookTime: '20-25',
      favorite: false,
      origins: ['Indian'],
      stars: 4.0,
      imageUrl: 'https://www.licious.in/blog/wp-content/uploads/2022/08/Shutterstock_1508653862.jpg',
      tags: ['fastfood', 'veg', 'snacks'],
    },
    {
      id:'12',
      name: 'Biryani',
      price: 10,
      cookTime: '10-15',
      favorite: true,
      origins: ['indian'],
      stars: 4.0,
      imageUrl: 'https://recipes.net/wp-content/uploads/2023/05/air-fryer-chicken-biryani-recipe_6968eb6ab4a5ae22d136dab86c9ea8af.jpeg',
      tags: ['slowfood', 'veg', 'lunch'],
    },
]

export const sample_tags:any[] = [
{ name: 'All', count: 12 },
{ name: 'FastFood', count: 8 },
{ name: 'Pizza', count: 3 },
{ name: 'Lunch', count: 7 },
{ name: 'SlowFood', count: 4 },
{ name: 'Hamburger', count: 2 },
{ name: 'Fry', count: 1 },
{ name: 'Soup', count: 1 },
{ name: 'Veg', count: 3 },
]

export const sample_users:any[] = [
{
    name:'Gaurav Yadav',
    email: 'yadav.gaurav80577@gmail.com',
    password : 'gaurav123',
    address : 'Jalandhar, Punjab',
    isAdmin:true
},
{
    name:'Dheeraj',
    email: 'dheeraj@gmail.com',
    password : 'dheeraj123',
    address : 'Jalandhar, Punjab',
    isAdmin:false
}
]
